### ISSUE TITLE
Mpq::ratio is unsafe

### ISSUE THREAD

**Issue by Rufflewind** [fizyk20/rust-gmp#21]
`Mpq::ratio` is unsafe:

```rust
extern crate gmp;
use gmp::mpq::Mpq;
use gmp::mpz::Mpz;
fn main() {
    println!("{:?}", Mpq::ratio(&Mpz::one(), &-Mpz::one()));
    //                                        ^--- (!)
}
```

results in:

```sh
zsh: segmentation fault (core dumped)
```

Tested this using gmp-6.1.2 on Arch Linux.

To quote the [manual](https://gmplib.org/manual/Applying-Integer-Functions.html):

> Note that if an assignment to the numerator and/or denominator could take an `mpq_t` out of the canonical form described at the start of this chapter (see [Rational Number Functions](https://gmplib.org/manual/Rational-Number-Functions.html#Rational-Number-Functions)) then `mpq_canonicalize` must be called before any other `mpq` functions are applied to that `mpq_t`.

There are probably other rational functions that need to be scrutinized as well.

**Comment by vks** [comment]
`Mpq::from_str_radix` is also affected. #22 should fix this.
