### ISSUE TITLE
Duplicated crates of rust-gmp ?

### ISSUE THREAD

**Issue by yvan-sraka** [fizyk20/rust-gmp#28]
I'm a bit confused, looking on https://crates.io/ for a rust wrapper for the GMP library I found both:

- [`rust-gmp = "0.5.0"`](https://crates.io/crates/rust-gmp)
- [`gmp = "0.3.1"`](https://crates.io/crates/gmp)

linking this GitHub repository!

**Comment by fizyk20** [comment]
Oh, interesting. I haven't been aware of `gmp`, somebody else published that. I'm only the owner of `rust-gmp`.

**Comment by tcharding** [comment]
I've investigated this issue, findings are:

- March 2014 @fizyk20 publishes v0.3.0 under package name `rust-gmp`
- July 2016: Someone called xcodevn publishes v0.3.1 under package name `gmp`  
- xcodevn disappeared  off of github or crates.io 4 years ago, there is an xcodevn on reddit so I messaged him to see if its the same person.

It would be nice to get `gmp` deleted from crates.io. If I can manage that would you consider re-publishing this as `gmp` @fizyk20?  (Seems like a nice convention to call the repo `rust-foo` and the package plain `foo`.)

EDIT: Oooh, you use `#![crate_name = "gmp"]` to imitate this behaviour - boy that was confusing me.

**Comment by ghost** [comment]
Hi! I'm xcodevn the owner of `gmp` package on `crates.io`. It seems that 4 years ago, I cloned fizyk20 repo and published it on `crates.io`. I don't remember why did I do that but it is my fault.

I've just tried to delete `gmp` package but not successful, `crates.io` prevents the deletion of packages to avoid dependency problems. So I've yanked the package instead! If anyone knows how to delete a package on `crates.io`, please let me know.

I'm also happy to transfer the ownership to @fizyk20, so this repo can be published under `gmp` name if @fizyk20 wants to do so.

**Comment by tcharding** [comment]
Legend, thanks! I read that we can contact the humans at crates.io and they might fix it up for us, if that's what we want to do.

**Comment by andersk** [comment]
Avoiding dependency problems is a *good reason* to prevent deletion of packages! We shouldn’t request to override that just to make things tidier (nor, I expect, would such a request be approved).

**Comment by tcharding** [comment]
> Avoiding dependency problems is a _good reason_ to prevent deletion of packages! We shouldn’t request to override that just to make things tidier (nor, I expect, would such a request be approved).

Is it  in anyone's best interest to be depending on a stale crate (here v0.3.1), possibly accidentally? Wouldn't it be better for users of `gmp` if this crate was yanked to force them to either update or depend on a version where they can control more than just a single version?

**Comment by vks** [comment]
On Wed, Feb 10, 2021, 09:38 Tobin C. Harding <notifications@github.com>
wrote:

> Avoiding dependency problems is a *good reason* to prevent deletion of
> packages! We shouldn’t request to override that just to make things tidier
> (nor, I expect, would such a request be approved).
>
> Is it in anyone's best interest to be depending on a stale crate (here
> v0.3.1), possibly accidentally?
>
This is already achieved for any new dependencies by yanking the crate. The
advantage is that it does not break builds.

> Wouldn't it be better for users of gmp if this crate was yanked to force
> them to either update or depend on a version where they can control more
> than just a single version?
>
I think it was already yanked?

>

**Comment by tcharding** [comment]
I think this issue is now resolved and can be closed since @xcodevn yanked `gmp`.
